API_HOST = 'https://qa-scooter.praktikum-services.ru'
CREATE_COURIER = API_HOST + '/api/v1/courier'
DELETE_COURIER = API_HOST + '/api/v1/courier/'
LOGIN_COURIER = API_HOST + '/api/v1/courier/login'
CREATE_ORDER = API_HOST + '/api/v1/orders'
GET_ORDERS = API_HOST + '/api/v1/orders'